### ISSUE TITLE
Not compatible with Lolipop

### ISSUE THREAD

**Issue by themiguelamador** [Skarafaz/NetworkMonitoredBlocker#2]
Does not work in Android 5.0 or 5.1.

**Comment by Skarafaz** [comment]
I know. There is no reason to use this module in Lollipop, the notification popups on startup and can be dismissed.

**Comment by RalfJung** [comment]
I absolutely disagree. I reboot my phone frequently, and having to dismiss the popup all the time is very annoying. It also makes me angry each time I see it - this iy my device, and I should be able to add my own certificates to it without any scary FUD.

**Comment by RalfJung** [comment]
*doh* it never occurred to me that I could use the feature to permanently dismiss a notification on this one. That seems to have worked. I hope this didn't disable more notifications than I intended^^

**Comment by themiguelamador** [comment]
My concern with that feature is if other notification come along and becomes blocked....

**Comment by RalfJung** [comment]
That's actually exactly the case - after permanently dismissing this notification, I do no longer get the notification when I reach my data limit. So that's a no-go.

In other words, there is still a strong need for blocking the "network may be monitored" on Android 5. I reboot my phone daily (not uncommon for anybody tracking the nightly branch of their ROM), so this notifications actually is actively annoying.

**Comment by RalfJung** [comment]
I forked this project, adding support for Android Lollipop: <https://github.com/RalfJung/noFUDroid>.

**Comment by Skarafaz** [comment]
Good job! ;-)
